name: micard
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-146.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
   - images/Nishtha.png

  fonts:
  - family: Pacifico
    fonts:
      - asset: fonts/Pacifico-Regular.ttf

  - family: DidactGothic
    fonts:
      - asset: fonts/DidactGothic-Regular.ttf